name: Checkout Azure Repo


on:
  push:
    branches:
      - main

jobs:
  checkout-repo:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
      with:
        submodules: false
    
    - name: Set Git config
      run: |
        git config --global user.name "Tibi"
        git config --global user.email "evil@evils.live"

    - name: Checkout Azure Repository
      uses: bancolombia/checkout-azure-repo@v1
      with:
        token: ${{ secrets.AZURE_TOKEN }}
        username: ${{ secrets.AZURE_USERNAME }}
        repo_url: ${{ secrets.AZURE_REPO_URL }}
  
    - name: Clone repository
      run: |
        git clone https://${{ secrets.AZURE_USERNAME }}:${{ secrets.AZURE_TOKEN }}@${{ secrets.AZURE_REPO_URL }} horvathtamas0440
      

