name: Checkout Azure Repo


on:
  push:
    branches:
      - main  # Vagy más ág, amelyen szeretnéd futtatni

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Set git config
        shell: bash
        run: |
          git config --global user.name "ltcevil"
          git config --global user.email "evil@evils.live"
      - name: Checkout Azure Repository
        uses: ltcevil/checkout-azure-repo@main
        with:
          token: ${{ secrets.AZURE_TOKEN }}  # Az Azure token tárolva a GitHub Secrets-ben
          username: ${{ secrets.AZURE_USERNAME }}  # Az Azure felhasználónév tárolva a GitHub Secrets-ben
          repo_url: ${{ secrets.REPO_URL }}


